services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-ppass"]
      interval: 10s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 10s
      retries: 10

  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

